@startuml

' Simplified sequence

actor User

participant "Launcher UI" as UI
participant LauncherEngine
participant OperationManager
participant OperationResolver
participant OperationFactory
participant LaunchOperation
participant ExecutionStrategy
participant LauncherStateMachine

User -> UI: Click launch
UI -> LauncherEngine : launch(configuration)
LauncherEngine -> LauncherStateMachine : transition(LOADING_MANIFEST)
LauncherEngine -> OperationManager : execute(LOAD_MANIFEST, context)
OperationManager -> OperationFactory : create(LOAD_MANIFEST, context, strategy)
OperationFactory --> OperationManager : LaunchOperation
OperationManager -> LaunchOperation : execute()
LaunchOperation -> ExecutionStrategy : execute(tasks, context)
ExecutionStrategy -> LauncherTask : execute(context)
LauncherTask --> ExecutionStrategy : Result
ExecutionStrategy --> LaunchOperation : OperationResult
LaunchOperation --> OperationManager : OperationResult
OperationManager --> LauncherEngine : OperationResult
LauncherEngine -> LauncherStateMachine : transition(RUNNING)
LauncherEngine --> UI : Success

@enduml