rootProject.name = "launcher"
include("launcher-ui")
include("launcher-core")
include("launcher-api")
include("launcher-downloader")
include("launcher-game")
include("launcher-natives")
include("launcher-common")
include("launcher-auth")
include("launcher-model")
include("launcher-storage")
include("launcher-verification")
include("launcher-app")
include("docs")
