@startuml

interface Credentials

class AuthenticationRequest
class UsernamePasswordCredentials
class OfflineCredentials

AuthenticationRequest --> Credentials
Credentials <|-- UsernamePasswordCredentials
Credentials <|-- OfflineCredentials

@enduml