@startuml

package "launcher-app" {}
package "launcher-ui" {}
package "launcher-core" {}
package "launcher-api" {}
package "launcher-verification" {}
package "launcher-storage" {}
package "launcher-model" {}

"launcher-app" --> "launcher-ui"
"launcher-app" --> "launcher-core"

"launcher-ui" --> "launcher-core"

"launcher-core" --> "launcher-api"
"launcher-core" --> "launcher-model"

"launcher-core" --> "launcher-verification"
"launcher-core" --> "launcher-storage"

"launcher-verification" --> "launcher-storage"
"launcher-verification" --> "launcher-model"

"launcher-storage" --> "launcher-model"

@enduml