@startuml
class LauncherEngine <<Singleton>>
class TaskPipeline <<Singleton>>
class VerificationTask <<Singleton>> {
    + Если задачи\n создаются один раз\n при сборке приложения
}
class LauncherTask <<interface>>
class VerificationService <<Singleton>>
class FileVerifier <<Singleton>>
class HashVerifier <<Singleton>>
class FileStorage <<Singleton>>

LauncherEngine --> TaskPipeline
VerificationTask ..|> LauncherTask
TaskPipeline --> VerificationTask
VerificationTask --> VerificationService
VerificationService --> FileVerifier
FileVerifier --> HashVerifier
FileVerifier --> FileStorage
@enduml