@startuml
VerificationService --> FileVerifier: verify(file)
FileVerifier --> FileStorage: exists(path)
FileStorage --> FileVerifier: true
FileVerifier --> FileStorage: size(path)
FileStorage --> FileVerifier: size
FileVerifier --> HashVerifier: calculateSha(path)
HashVerifier --> FileVerifier: sha256
FileVerifier --> FileVerificationResult: createResult(...)
FileVerificationResult --> VerificationService
@enduml